fix(updateloop): inserting empty gallery into database
This will cause the "server" field to be empty, causing that the "server" enum check to fail. The reason of this is that we didn't check whether the id exists in the map or not. If the id didn't exist in the map, it would return a zero value of gallery and it was inserted into the galleries slice.

```
2023/11/13 14:12:30 /app/internal/app/gallery/repository.go:84 ERROR: invalid input value for enum game_server: "" (SQLSTATE 22P02)
[29.222ms] [rows:0] INSERT INTO "gallery_galleries" ("server","id","name","description") VALUES ('CN','act13side','长夜临光','耀骑士的归来，
将这一届特别锦标赛推往了一个新的高潮。
同时，在霓虹灯没有照到的角落，
那些被消失的怒吼也即将冲破桎梏。
舞台之上，骑士之路交错蔓延。
舞台之下，城市之殇箭在弦上。
他们终将交汇......'),('CN','act25side','孤星','克丽斯腾的失踪牵动了所有人的思绪。
军方与梅兰德基金会齐聚特里蒙，
凯尔希选择主动介入。
乌云密布，暴雨将至。
是阴谋，是闹剧，还是独醒？
往昔的恩怨于此地交会，过去与未来在此地碰撞。
这一夜，无人入眠。'),('CN','act17side','愚人号','在静谧中沉没的国度，将他们的明珠遗落海上。
猎人们循着传说寻找同胞遗产，线索汇聚，指向一处。
斯图提斐拉，黄金的大船，文明的丰碑。
人类必须联成一线，凯尔希如此警告。
伊比利亚早已看不见大海，阿戈尔亦遭异血洗礼。
唯有海洋，孕育生命；唯有海洋，亘古不变。'),('','','',''),('CN','rogue_2','水月与深蓝之树','海风从肩旁吹过，去往大海的另外一端。
你的终点正在那里，而此时的你尚未起步。
收拾行李，做好准备，大海等待着你的到来。'),('CN','rogue_1','傀影与猩红孤钻','天色渐暗，你迷失在了雾气笼罩的森林间。
你急需寻找一处安全的避难所来度过这个夜晚，
而眼前这座不祥的古堡，便是唯一的选择。 '),('CN','rogue_3','探索者的银凇止境','物资准备齐整，人员集结完毕。
你与探险者们离开萨米南疆的城市，向北方进发。
行过萨米，穿过冰原，未知的面纱终将被揭开。') ON CONFLICT ("server","id") DO UPDATE SET "name"="excluded"."name","description"="excluded"."description"
2:12PM ERR Update loop failed to update the stories error="ERROR: invalid input value for enum game_server: \"\" (SQLSTATE 22P02)" localVersion=23-10-18-08-57-00-a2b96e remoteVersion=23-11-06-08-03-08-a68b02 server=CN
```